### ISSUE TITLE
score is not added in the Movie class

### ISSUE THREAD

**Issue by GhalebKhaled** [moogar0880/PyTrakt#106]
Hi
I can see there is a `score` field in the response but can't find it in in the `Movie` class in this library

https://trakt.docs.apiary.io/#reference/search/text-query/get-text-query-results

I want this field, is there a way to get it?

**Comment by moogar0880** [comment]
@GhalebKhaled I've added a new search API in #108 that I think should address this issue. The `score` field isn't actually a part of the movie/show/episode, it's a part of the search result that `search` was just dropping on the floor in favor of the actual pieces of media.

It also looks like a few other things about their search API have changed since those functions were originally written, so this change should improve search results across the board.

To get the scores you can use the new `trakt.sync.get_search_results` function. The results from that will have the score and media items included.

If you run into any issues with that feel free to re-open this issue or open a new one

**Comment by GhalebKhaled** [comment]
many thanks @moogar0880, this makes sense, I'll check your suggested API
