### ISSUE TITLE
Enumerate list items

### ISSUE THREAD

**Issue by permster** [moogar0880/PyTrakt#46]
I may be missing it but is there any way to enumerate list items?  I can get a list of custom lists and I can get a specific list object but I'm not seeing a built in method for enumerating list **items**.

See Trakt API here: http://docs.trakt.apiary.io/reference/users/list-items/get-items-on-a-custom-list

**Comment by moogar0880** [comment]
maybe I'm misunderstanding, but is there a reason that the builtin `enumerate` function won't work?

**Comment by permster** [comment]
I'm probably overlooking something simple here.  I'm trying to enumerate list items in a for loop.

`list_test = UserList.get('listname', 'listcreator')`
`for item in list_test:`
`	print item`

If I do a print list_test it gives me the list name, slug, etc. but I'm trying to loop through the list items and not getting it.

**Comment by permster** [comment]
The more I look at this I don't think it's been implemented.  The link in my first post shows a get against:  https://api-v2launch.trakt.tv/users/username/lists/id/items

The only places I'm seeing that used already are for adding and removing items from a list.  Not just getting the items.  I'll play around with this logic in my fork.

**Comment by permster** [comment]
I've been playing around with this some and it looks like this is going to be a bit of an undertaking.  It should probably be in it's own class in users.py like class ListItems() or UserListItems().  The JSON data that gets returned can be movies, shows, seasons, episodes, or people which is where the rub is.  See the sample JSON data file below.  It's a list and each item in the list is a tuple.  I assume it's just a matter of looping through the return to pick out the movies, shows, seasons, episodes, and people and doing a _get to populate the rest of the information.

[sample_json_data.txt](https://github.com/moogar0880/PyTrakt/files/152265/sample_json_data.txt)

I'll keep hammering away but it may be a while as I'm still learning Python.

**Comment by moogar0880** [comment]
Sorry about the delay in response, things have been a bit hectic lately. 

From what I can tell, it looks like trakt, at some point in time, returned an `items` array when you did a `GET` for a specific list, which contained all of the items in that list. But, as you've discovered, this is no longer the case. Glad to hear that you're not shying away from trying to get that functionality working, it's always good to have help on projects like this :smile: 

Currently I'm working on trying to get the testing for this library up to snuff so that as the API changes it will hopefully be more obvious when things break. And as a part of that I'm also doing an audit on what functionality isn't covered by this module, so I'll be sure to add this to the list for now.

If I can be of assistance please feel free to bug me. I'm hoping that I'll be able to start putting more of my free time into my open source projects again in the near future

**Comment by permster** [comment]
Here's my first and probably poor attempt at making this work.  Please let me know what you think.
40378c298a8954c168b18cd063b257c382106496

I added a new method to the UserList class called get_items() which sets the self._items() to whatever class instances are in the list.  I'm sure there's a better way to implement this so feel free to grab my logic out of there.

Enumerating through the list will require checking isinstance for movie, tvshow, tvepisode, etc. since it can be one or more of those types.

I ran into one issue with the @get decorator because it shares the same name as the UserList get() method so it can't be used more than once.  This issue required me to modify the import at the top of users.py and all decorators in users.py to a different name.

It's hard to explain so if you want to discuss this further I would be more than happy to and I'm hoping you know of an easy way around this without having to do what I did or having to rename the UserList.get() method which would break things.

**Comment by permster** [comment]
I made a few changes to help simplify the for loop I added just a bit.
https://github.com/permster/PyTrakt/blob/develop/trakt/users.py

**Comment by moogar0880** [comment]
The bulk of these changes look good if you'd like to open a pull request with them. 

I'd be curious to hear more about the `get` naming issue, because a `get` function in the module's namespace and a class method shouldn't hit a conflict. For instance, the following snippet worked for me.

```python
>>> def foo(x): 
...    return x

>>> class Bar:
...    @foo
...    def foo(self):
...        print('baz')
>>> b = Bar()
>>> b.foo()
... baz
```
Which version of python were you seeing that under?

Also, it would be great if you could add some tests for these new calls with some mocked responses. If you take a look in the [tests directory](https://github.com/moogar0880/PyTrakt/tree/master/tests) you'll see some other examples in there. It might not be the most intuitive setup so if you hit any issues with that please let me know. I'd like to add some docs on writing tests with the setup I have in place.

Also, not sure if it will matter but I'm heading out on vacation tomorrow, so my response time will probably, in reality be about what it usually is, but may also be a bit longer.

As always, thanks for the contributions 😄

**Comment by permster** [comment]
I'm running Python 2.7.11.  I'll try and find a test scenario for you on the decorator issue but the easiest way to see it yourself is to take my code and change all @getd decorators back to @get and change the import for get at the top back to your original.  You should see the issue.

I'll start looking at creating some test logic for the new code.  Should just be a simple for loop checking for isinstance.

One last question is whether or not this logic should be a part of the existing get() function or a separate get_items() function like I chose to do?  My logic behind that was that there may be people only wanting basic list information.  If it was in get() it may be taxing (for large lists) to also populate the list items as well.  Just wondering what your thoughts are on that?  I suppose it could also be an optional argument on get() if they want to get the list items as well plus separately callable using get_items().  I think I'll play around with that logic a bit.

**Comment by permster** [comment]
Actually scratch my last paragraph from previous reply.  Based on the fact that the current UserList iteration doesn't work I'm going to have the get function go ahead and return the list items by default.  See my changes here: c6d3ce9

**Comment by permster** [comment]
Quite a few changes commited to my dev branch.  Biggest changes were around the fact that the list items don't return a full set of information for the movie, show, season, etc.  So now I've modified the code so it does an extended=full for each list item to retrieve all the data for each item.  I also updated some of the json files and test_users.py for the new test case I added.  I ran into one issue with conftest.py where it was erroring with IOError: [Errno 2] No such file or directory so I had to change:
`MOCK_DATA_DIR = os.path.abspath('tests/mock_data')`
to
`MOCK_DATA_DIR = os.path.abspath('mock_data')`

I didn't check it in since I think that may just be an issue on my end.

Here are the changes:  752077b

I'm holding off on the pull request for now until I can figure out the decorator issue I mentioned before in users.py.  I hope there's an easier workaround instead of what I did.

**Comment by moogar0880** [comment]
So, after playing around with your develop branch for a bit I too am hitting the same issue. I was able to get it working by renaming `get` to `_get` and, after the class definition, doing 
```
UserList.get = UserList._get
```
 It's a little hacky, but it's able to successfully parse the class without hitting those `TypeError`'s. 

I suppose that another option might be to write a metaclass that will do that aliasing for you, but I think that would probably be overkill here

**Comment by permster** [comment]
Sorry had some troubles with conflicts on my master branch but it should be all set now.

**Comment by moogar0880** [comment]
I'm not too worried about the `extended=full` calls, the fix for that is pretty not trivial, and I think would result in a weird user experience for the end user
