### ISSUE TITLE
V2 API

### ISSUE THREAD

**Issue by stampedeboss** [moogar0880/PyTrakt#5]
Is any work being done on the V2 API of trakt.

**Comment by moogar0880** [comment]
In short, yes. Sort of. The folks over at trakt.tv haven't made this an easy transition. However, I do have some `GET` related v2 functionality in place that I can push to a v2 branch for now.

I started playing around with v2 a bit but I haven't gotten very far in porting PyTrakt yet, mainly because of authentication issues. In particular though, they've completely changed how to send auth data. It looks like this library is going to require someone from trakt.tv support to register PyTrakt as a media center. Which, honestly, seems like a bit of hassle, but since they've gotten rid of user specific API keys and have locked down the `/login/` uri to _registered_ media center applications only, that's going to be the only way for any `POST` calls to work (barring OAuth2, and there's no way I'm spinning up a server for and OAuth2 authentication system)

Per their API documentation:
> In order to fall under this special use case, you will need to contact the trakt staff and get a special allowance made

I suppose now's as good a time as any to go ahead and try to get this application registered as a media center, so I'll get that process started. But given that this isn't _actually_ a media center I'm not sure how well that will be received. I can't imagine that they wouldn't approve the request but should they, for some reason, not make an allowance for this module, that will probably be the end of it's usefulness. But that's worst case scenario, and hopefully it won't come to that!

I'll get in touch with trakt support and report in when I hear something back from them

**Comment by stampedeboss** [comment]
I've got most of the OAUTH2 worked out, no server is needed.  There is a
one time cut and paste that would be required to generate the token, plus
the application would need to be able to store the token for future use..
I'm working building it into a callable module.

Only issue is for multiple users, I'm getting 403, but for my account it's
working perfectly.

AJ Reynolds
817-846-1455

**Comment by moogar0880** [comment]
Really? I was under the impression that you needed to have your own OAuth2 service that Trakt's OAuth system would talk to? (Admittedly I know very little about OAuth)

And in that case I'd love to see what you've got done, I've had zero success with their OAuth calls

**Comment by stampedeboss** [comment]
from requests_oauthlib import OAuth2Session

client_id = 'Get it for the registered app using the package'
client_secret = 'Get it for the registered app using the package'
redirect_uri = 'urn:ietf:wg:oauth:2.0:oob'
username = 'trakt username'

authorization_base_url = 'https://api.trakt.tv/oauth/authorize'
token_url = 'https://api.trakt.tv/oauth/token'

headers = {'Content-Type': 'application/json'}

# OAuth endpoints given in the API documentation
oauth = OAuth2Session(client_id, redirect_uri=redirect_uri, state=None)

# Redirect user to Trakt for authorization
authorization_url, state = oauth.authorization_url(authorization_base_url,
username=username)
print 'Please go here and authorize,', authorization_url

# Get the authorization verifier code from the callback url
redirect_response = raw_input('Paste the Code returned here:')

# Fetch the access token
oauth.fetch_token(token_url, client_secret=client_secret,
        code=redirect_response)

print oauth.token


This is a one time process for each user using your application, it returns
a token that is used going forward.  In reality, PyTrakt doesn't need to be
authorized, it's what ever someone builds using it, we just need to supply
the functions to interact.  I would be happy to assist in updating PyTrakt,
I am working on making the getToken process more consistent and callable.

The key part for me was to realize it would open the browser and have the
user authorize then it would present a temporary token that had to be cut
and pasted back into the python stream.  That's why the server isn't needed
you just have them do a cut and paste to continue.  Give it a try.

From that point forward you use the generated token to authorize the
interactions.  The following is an example I used to test and it works
without issue.

    def getCollection(self, userid):

        headers = {
          'Content-Type': 'application/json',
          'trakt-api-version': '2',
          'trakt-api-key': token[userid]['client_id'],
          'Authorization': token[userid]['authorization']
        }

        request = Request('
https://api.trakt.tv/users/{}/collection/shows'.format(userid),
headers=headers)
        response_body = urlopen(request).read()
        data = json.loads(response_body.decode('UTF-8', 'ignore'))

        for show in data:
            self._collected.append(Series(**show))

        return self._collected


The one, of many, issues with the trakt v2 upgrade is until your registered
application is "Approved" you can only access you own account.  They really
blew this, and it may end up costing them alot of users.  I've considered
moving to another tool.  I have been unable to get a list of series in a
collection for a few weeks.


On Sat, Jan 24, 2015 at 12:35 PM, Jon Nappi <notifications@github.com>
wrote:

> Really? I was under the impression that you needed to have your own OAuth2
> service that Trakt's OAuth system would talk to? (Admittedly I know very
> little about OAuth)
>
> And in that case I'd love to see what you've got done, I've had zero
> success with their OAuth calls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moogar0880/PyTrakt/issues/5#issuecomment-71331238>.
>



-- 
AJ Reynolds

**Comment by moogar0880** [comment]
Well working with the v2 api hasn't exactly been a walk in the park, but with only some minimal tweaks to the code you provided (and some dumb luck) I was finally able to get some API calls working.

Looking through their documentation it looks like there are some API calls that aren't even turned on yet, so it's going to be interesting to see what working with those is going to be like. But I'll spend some time on this over the next couple of days and try to get something functional out there.

And I completely agree, this was definitely not the most graceful release I've ever seen. It does looks like they're slowly rolling out patches though, so fingers crossed that they can smooth over some of these rough edges
