### ISSUE TITLE
API in development?

### ISSUE THREAD

**Issue by emouawad** [moogar0880/PyTrakt#92]
Hello, I have just come across this lib while trying to find a way to use trakt api in python.
Tried some of the api calls and it works. It seems to me, development has been stopped for this? Since i noticed a promising To-Do list - would be great if we had all that! ;) Any technical reasons for not implementing it all? thanks for the Authors & contributors, cheers 😄

**Comment by moogar0880** [comment]
Hey @emouawad, thanks for reaching out. 

There's no technical reason that the Todo list hasn't been implemented yet (at least not as of the last time I updated that list). I don't think I'd say that development has _stopped_, but this project isn't at the top of _my_ to-do list these days so it's definitely slowed down. That being said, if there are features that users want to see added, I'd be happy to help get them in. 

Naturally, if you want a new feature added quickly the best way will probably be to open a pull request that adds the functionality you're looking for. But if there's some larger feature or something that you're otherwise not comfortable adding, you can always open an issue for it and myself or one of the other more frequent contributors should be able to help out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
